name: Deploy to Firebase Hosting on cron
'on':
  workflow_dispatch:
  schedule:
    - cron: '0 * * * 1-5'
jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install dependencies
        run: npm ci

      - name: Build site
        run: npm run build
        env:
          ELEVENTY_ENV: prod

      - name: Verify new version
        run: npm run version-check
        env:
          GITHUB_SHA: ${{ secrets.GITHUB_SHA }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Deploy site to Firebase
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_WEB_DEV_PRODUCTION_1 }}'
          projectId: web-dev-production-1
          channelId: live

      - name: Algolia index site
        run: npm run algolia
        env:
          ALGOLIA_APP_ID: ${{ secrets.ALGOLIA_APP_ID }}
          ALGOLIA_API_KEY: ${{ secrets.ALGOLIA_API_KEY }}
