name: Percy

# By default, runs when a pull_request's activity type is opened, synchronize,
# or reopened
on:
  push:
    branches:
      - main
    paths:
      - 'src/**.js'
      - 'shared/**.js'
      - '!src/site/_data/countries.js'
      - 'package.json'
      - '**.njk'
      - '**.scss'
  pull_request:
    paths:
      - '.github/workflows/percy-workflow.yml'
      - 'src/**.js'
      - 'shared/**.js'
      - '!src/site/_data/countries.js'
      - 'package.json'
      - '**.njk'
      - '**.scss'

jobs:
  percy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 1

      - name: Install
        run: npm ci

      - name: Percy
        env:
          NODE_OPTIONS: "--max-old-space-size=8192"
          PERCY_TOKEN: ${{ secrets.PERCY_TOKEN }}
        run: npm run percy
