name: Snapshot firestore
on:
  schedule:
    # At 19:00 UTC / 7:00 PST on every Monday.
    - cron: '0 19 * * 1'

jobs:
  ci:
    name: Run gcloud to snapshot
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup gcloud
        uses: google-github-actions/setup-gcloud@v0.2.0
        with:
          version: '290.0.1'
          service_account_email: ${{ secrets.GCLOUD_EMAIL }}
          service_account_key: ${{ secrets.GCLOUD_KEY }}
          export_default_credentials: true

      # nb. gcloud uses a new timestamp'ed dir only when pointing at a top-level bucket. Thus, we
      # can't naÃ¯vely target a subfolder (it will fail with "Path already exists").
      # This is a secondary bucket, not the default Firebase project. Its lifecycle config is set
      # to delete objects that are >=90 days old.
      - name: Export Firestore
        run: gcloud --project web-dev-production-1 firestore export gs://web-dev-production-firestore-archive
